#ifndef KEYWORDS_H
#define KEYWORDS_H

/* diminuir isso... sera compativel para c99 */
const char *keywords[] = {
        "extern",
        "short",
        "while",
        "break",
        "float",
        "signed",
        "_Alignas",
        "case",
        "for",
        "sizeof",
        "_Alignof",
        "char",
        "goto",
        "static",
        "_Atomic",
        "const",
        "if",
        "struct",
        "_Bool",
        "continue",
        "inline",
        "switch",
        "_Complex",
        "default",
        "int",
        "typedef",
        "_Generic",
        "do",
        "long",
        "union",
        "_Imaginary",
        "double",
        "register",
        "unsigned",
        "_Noreturn",
        "else",
        "restrict",
        "void",
        "_Static_assert",
        "enum",
        "return",
        "volatile",
        "_Thread_local",
};

#endif
